image: python:3.10-alpine

before_script:
  - pip install mkdocs-material tomli snakemd

pages:
  stage: deploy
  script:
    - python convert_toml2md.py toml/ docs/
    - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

